INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (1,'RHZOG','9 de Julio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (2,'HXXQL','A. de la Cruz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (3,'JUBXH','Abasto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (4,'NKMLS','Abbott',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (5,'ZNAHB','Abel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (6,'VQSES','Acassuso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (7,'VJQNU','Acevedo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (8,'OZWKF','Achupallas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (9,'EFCRT','Adela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (10,'UPLLK','Adolfo Gonzales Chaves',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (11,'ADROG','Adrogué',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (12,'IIENP','Agote',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (13,'SWPMM','Aguas Verdes',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (14,'XESJT','Agustin Roca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (15,'FORTI','Agustina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (16,'GTEAD','Alagón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (17,'TJKCT','Alastuey',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (18,'YYUUA','Albariño',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (19,'GCEPD','Alberdi Viejo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (20,'VPTNE','Alberti',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (21,'WJDMY','Aldea Romana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (22,'PKBPY','Aldo Bonzi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (23,'MOSQF','Alegre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (24,'ZATZO','Alejandro Korn',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (25,'QGHNT','Alejandro Petión',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (26,'FCQAR','Alférez San Martín',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (27,'OJJYC','Algarrobo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (28,'CYMWM','Almirante Brown',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (29,'SLMLT','Almirante Solier',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (30,'NSAHP','Alsina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (31,'ZIKTW','Alta Vista',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (32,'IYRAK','Altamira',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (33,'ZFLYA','Altamirano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (34,'VDPZN','Altona',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (35,'ZZNJM','Amalia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (36,'KCHIG','Anasagasti',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (37,'NRJML','Ancón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (38,'XLZHC','Andant',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (39,'BNCVQ','Anderson',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (40,'YYHJY','Antonio Carboni',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (41,'MXYLJ','Aparicio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (42,'IIAUN','Apeadero Punke',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (43,'FXOQH','Aragón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (44,'DKULK','Arana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (45,'CGFKL','Arano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (46,'ATYFS','Araujo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (47,'IPCAA','Arboledas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (48,'RDSSP','Arenaza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (49,'MYBOE','Argerich',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (50,'SUMLJ','Ariel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (51,'JIQWH','Arrecifes',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (52,'XNBVO','Arribenos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (53,'JFMZA','Arroyo Corto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (54,'PMCBW','Arroyo Dulce',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (55,'URGSW','Arroyo Venado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (56,'UPMRW','Arroyo de la Cruz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (57,'VDVYA','Arroyo de los Huesos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (58,'NOQFD','Arroyo del Medio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (59,'ARTSG','Arturo Segui',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (60,'XLJIA','Arturo Vatteone',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (61,'MXCEM','Asamblea',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (62,'FPISK','Ascension',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (63,'ANEUS','Asturias',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (64,'IWCMS','Atalaya',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (65,'NLVQX','Atilio Pessagno',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (66,'XOXSS','Atucha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (67,'JSIXZ','Avellaneda',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (68,'EPATF','Avestruz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (69,'OMWUZ','Ayacucho',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (70,'IMCDC','Azcuenaga',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (71,'UOOXT','Azopardo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (72,'OIOZX','Azucena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (73,'GWSVU','Azul',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (74,'BHI','Bahia Blanca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (75,'HTGTN','Baigorrita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (76,'XNZPW','Bajo Hondo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (77,'BL1','Balcarce',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (78,'XJDWX','Balneario La Balandra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (79,'DMYBW','Balneario Los Angles',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (80,'AZZKS','Balneario Mar Chiquita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (81,'NNXYC','Balneario Oceano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (82,'GBKVL','Balneario Orense',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (83,'UMUFM','Balneario Oriente',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (84,'GJSNI','Balneario Pehuen-Co',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (85,'OIUFI','Balneario Reta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (86,'DHBHZ','Balneario Sauce Grande',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (87,'HLSAE','Balsa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (88,'ZUSWS','Bancalari',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (89,'SHJTG','Banderaló',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (90,'PKTRK','Banfield',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (91,'TJGFZ','Baradero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (92,'FDZWH','Barker',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (93,'HVZAV','Barrio Colinas Verdes',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (94,'EQAZG','Barrio de Suboficiales',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (95,'IQRPL','Barrow',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (96,'RHFPT','Batan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (97,'STSWO','Bathurst',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (98,'FGCDJ','Baudrix',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (99,'IQLAV','Bayauca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (100,'GMBZA','Beccar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (101,'GECIR','Bella Vista',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (102,'XIYVE','Bellocq',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (103,'PNOLQ','Benavidez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (104,'RTQUI','Benito Juárez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (105,'QYZLN','Benítez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (106,'BEFNE','Berazategui',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (107,'UMGDO','Berdier',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (108,'HUHMX','Berisso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (109,'VNFDB','Bermúdez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (110,'JFDYU','Bernal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (111,'ENKLV','Berraondo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (112,'TFHEG','Berutti',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (113,'RHFJB','Billinghurst',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (114,'LNIUK','Blanca Grande',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (115,'KLAKN','Blandengues',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (116,'QRTFU','Blaquier',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (117,'XLWPK','Blas Durañona',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (118,'STMEI','Bocayuva',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (119,'EFTKA','Bonnement',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (120,'KALKQ','Bordenave',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (121,'VNKJZ','Bordeu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (122,'LPDPQ','Bosch',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (123,'MVYXB','Bosques',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (124,'PPBRH','Boulevard Atlántico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (125,'DRCIL','Boulogne',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (126,'COJKE','Bragado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (127,'NUDPS','Buchanan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (128,'FQERL','Burzaco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (129,'PGNOT','Cabildo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (130,'AYAZI','Cachari',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (131,'TTIYU','Cadret',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (132,'YIWPK','Calderón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (133,'CZJOS','Calera Avellaneda',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (134,'LPBHB','Calfucurá',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (135,'QJFSC','Calvo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (136,'VGHPJ','Cambaceres',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (137,'PEWUW','Camet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (138,'CP1','Campana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (139,'HOKVB','Campanopolis',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (140,'VGZOH','Campodónico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (141,'BIOFN','Campos Salles',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (142,'GMPYE','Cangallo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (143,'KZXXI','Canning',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (144,'JEWPQ','Cantera Aguirre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (145,'IUASO','Canónigo Gorriti',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (146,'KBYYB','Capilla del Senor',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (147,'IHNOB','Capitan Sarmiento',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (148,'EPRPM','Capitán Castro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (149,'ZBQWW','Carabelas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (150,'YORDZ','Carapachay',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (151,'BOTPK','Caraza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (152,'SKPBZ','Cardenal Cagliero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (153,'ZDQRA','Carhue',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (154,'CA6','Cariló',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (155,'QDNHI','Carlos Begueríe',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (156,'GQJEG','Carlos Casares',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (157,'SBWXQ','Carlos Keen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (158,'YJESJ','Carlos María Naón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (159,'EBHEK','Carlos Salas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (160,'GAFUR','Carlos Tejedor',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (161,'SNMGJ','Carmen de Areco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (162,'CPG','Carmen de Patagones',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (163,'ODCZU','Casalins',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (164,'YZGSE','Casbas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (165,'UHLDK','Cascada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (166,'QLTXC','Caseros',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (167,'CKFUO','Casey',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (168,'WENGN','Castelar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (169,'GLOJR','Castelli',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (170,'ZDITA','Castilla',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (171,'VFCNS','Cazón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (172,'JJIEW','Cañada Seca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (173,'CL9','Cañuelas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (174,'RMSZU','Centenario',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (175,'TKDTB','Centinela del Mar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (176,'KUQAU','Centro Guerrero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (177,'MCQEW','Centro Urquiza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (178,'WLPGS','Cerrito',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (179,'OPLJX','Cerro Negro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (180,'MUBKM','Cerro Sotuyo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (181,'PHXFZ','Cerro de la Gloria',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (182,'GVELC','Chacabuco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (183,'XSMWU','Chancay',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (184,'FIVQT','Chapadmalal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (185,'XFNHW','Chapaleofú',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (186,'USECS','Chas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (187,'CH7','Chascomus',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (188,'EJGHY','Chasico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (189,'AYSVL','Chenaut',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (190,'XLTDR','Chiclana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (191,'ZXOYO','Chillar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (192,'LVTUJ','Chivilcoy',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (193,'RXPCS','Choiqué',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (194,'KIJMP','City Bell',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (195,'RTQTL','Ciudad General Belgrano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (196,'TETMR','Ciudadela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (197,'CYVPW','Claraz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (198,'CL5','Claromeco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (199,'YMKWM','Claudio Molina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (200,'AAIMK','Claypole',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (201,'PRVRR','Cobo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (202,'TONVQ','Cochrane',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (203,'SOVCD','Coliqueo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (204,'YRHZV','Colon',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (205,'OVOBE','Colonia Barragán',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (206,'ZQWST','Colonia Chapadmalal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (207,'RAUHI','Colonia Hinojo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (208,'PWNLP','Colonia Hogar Ricardo Gutiérrez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (209,'XPNVB','Colonia Martín Fierro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (210,'LAIUE','Colonia Mauricio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (211,'NIVTZ','Colonia Monte La Plata',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (212,'XGIFN','Colonia Nieves',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (213,'ISLON','Colonia San Martín',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (214,'YHBQI','Colonia San Miguel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (215,'TVBNN','Colonia San Miguel Arcangel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (216,'EWNPM','Colonia San Pedro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (217,'TADIH','Colonia Santa Rosa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (218,'VHKMC','Colonia Seré',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (219,'PPKBM','Colonia Vignaud',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (220,'DUSQQ','Colonia Vélaz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (221,'CDXCY','Comandante Giribone',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (222,'MYROI','Comandante Nicanor Otamendi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (223,'FLBMP','Comodoro Py',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (224,'TVRFW','Condarco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (225,'FBRAG','Conesa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (226,'XMKBL','Coraceros',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (227,'QHAYS','Corazzi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (228,'YTNAM','Corbett',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (229,'EKAHK','Coronel Boerr',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (230,'BD3','Coronel Brandsen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (231,'KYXNP','Coronel Charlone',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (232,'WDTWE','Coronel Dorrego',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (233,'UWXYQ','Coronel Falcón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (234,'ORANE','Coronel Granada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (235,'XVZFT','Coronel Isleño',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (236,'JARPM','Coronel Martínez de Hoz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (237,'SHLXN','Coronel Mom',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (238,'JPORI','Coronel Pringles',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (239,'LWYUA','Coronel Rodolfo Bunge',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (240,'LYEHE','Coronel Seguí',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (241,'CS7','Coronel Suarez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (242,'KNLWU','Coronel Vidal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (243,'LIPCL','Corti',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (244,'IMLWI','Cortines',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (245,'MPNQK','Costa Bonita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (246,'AUHHC','Costa Chica',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (247,'CSTES','Costa Esmeralda',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (248,'CE3','Costa del este',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (249,'LFEIG','Covello',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (250,'GTOUU','Cristiano Muerto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (251,'IFDXD','Crotto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (252,'LBNZI','Cuatro de Noviembre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (253,'OZCLI','Cucha Cucha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (254,'KBSBD','Cucullú',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (255,'EAKQU','Cura Malal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (256,'WBDRH','Curarú',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (257,'KUJUB','Daireaux',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (258,'OYSJC','Darregueira',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (259,'SSWZB','De Bary',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (260,'DHAII','De La Canal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (261,'ZGEZN','De la Garma',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (262,'DJOFG','Defferrari',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (263,'VOHOQ','Del Carril',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (264,'IFPCF','Del Valle',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (265,'DMRRA','Del Viso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (266,'ACQJV','Delfín Huergo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (267,'HCBQM','Delgado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (268,'TANPM','Delta del Tigre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (269,'KNYAS','Dennehy',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (270,'AUVOM','Diamante',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (271,'KNWSA','Diecisiete de Agosto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (272,'JLZBX','Dieciséis de Julio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (273,'PWKNS','Diego Gaynor',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (274,'PKLXO','Dique Lujan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (275,'JPYDD','Doce de Agosto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (276,'MASGG','Doce de Octubre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (277,'WDOWI','Dock Sud',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (278,'YQYWT','Doctor Domingo Harosteguy',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (279,'XSCPD','Dolores',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (280,'QJOCM','Domselaar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (281,'NUGEC','Don Bosco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (282,'ZCOHC','Don Cipriano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (283,'HPZIQ','Don Torcuato',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (284,'EGXUE','Dos Naciones',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (285,'LOTFQ','Doyhenard',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (286,'NDKLQ','Drabble',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (287,'ZPZYG','Drysdale',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (288,'HHWJY','Ducós',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (289,'AAVKL','Dudignac',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (290,'IRJGH','Dufaur',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (291,'NBIEB','Duggan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (292,'BNEUJ','Durañona',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (293,'QPXTK','Dussaud',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (294,'TUFAA','D’Orbigny',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (295,'AQKYE','Edmundo B. Perkins',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (296,'ECONB','Eduardo Costa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (297,'MXUJG','Egana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (298,'OAIII','El Arbolito',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (299,'TNDWR','El Boquerón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (300,'UZNQI','El Coyunco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (301,'CYWOF','El Divisorio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (302,'VKTMF','El Dorado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (303,'TTMYH','El Jabalí',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (304,'JAGUE','El Jagüel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (305,'MXJAF','El Lenguaraz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (306,'GCNYZ','El Mangrullo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (307,'JKMKM','El Moro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (308,'EXKOC','El Palomar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (309,'QISHX','El Paraíso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (310,'TGUBD','El Parche',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (311,'XZZXI','El Pensamiento',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (312,'BJVFM','El Porvenir',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (313,'DCOBL','El Recado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (314,'PIAYE','El Sauce',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (315,'TXRVL','El Socorro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (316,'GGGAM','El Talar de Pacheco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (317,'MSJFA','El Tejar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (318,'GQCWN','El Trigo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (319,'NLIPT','El Triunfo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (320,'UDCLV','El Verano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (321,'AODTB','El Zorro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (322,'RUCZB','Eldía',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (323,'MGNJG','Elordi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (324,'YNYYA','Elvira',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (325,'QUJHS','Elías Romero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (326,'OZVTI','Emiliano Reynoso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (327,'LCNLJ','Emilio Ayarza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (328,'HGTZK','Emilio Lamarca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (329,'SBRGS','Emilio V. Bunge',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (330,'PXVFT','Emita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (331,'EIFNV','Emma',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (332,'ZZECL','Empalme Lobos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (333,'VMWEJ','Empalme San Vicente',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (334,'PYTNC','Encina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (335,'LMHKV','Energía',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (336,'YFQQL','Enrique Fynn',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (337,'MROVW','Enrique Lavalle',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (338,'KXLWG','Ensenada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (339,'WMDMX','Ensenada Berisso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (340,'GFGYS','Erize',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (341,'IOIQH','Ernestina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (342,'XHCOE','Eréscano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (343,'POTWI','Escalada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (344,'EC1','Escobar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (345,'JWHNP','Escuela Italiana Colegio Da Vinci',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (346,'POBLR','Espartillar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (347,'WXMDN','Espigas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (348,'ZSFMC','Espora',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (349,'GSEYX','Esquina Negra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (350,'LSCJW','Estacion Ramallo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (351,'JFSQU','Estación Arenales',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (352,'AGQFB','Estación El Jabali',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (353,'RFNGK','Estanislao S. Zeballos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (354,'QEZRD','Esteban Agustín Gascón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (355,'AOXOP','Esteban Echeverria',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (356,'KTBGX','Esteban de Luca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (357,'EFFDR','Estela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (358,'OXPMD','Esther',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (359,'BDVBW','Estomba',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (360,'KZKRU','Estrugamou',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (361,'QSMLI','Etchegoyen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (362,'EZ1','Ezeiza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (363,'BKBVG','Ezpeleta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (364,'HMRRS','Fair',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (365,'VHBUM','Faro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (366,'ZBVBB','Fatima',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (367,'IVQSG','Fatraló',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (368,'KWKGT','Fauzón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (369,'FSAUB','Felipe Solá',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (370,'UHQTQ','Ferré',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (371,'EXKMZ','Fiorito',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (372,'WZDQO','Florencio Varela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (373,'SLYZV','Florentino Ameghino',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (374,'HASTR','Florida',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (375,'IXVJV','Florida Oeste',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (376,'DAHNK','Fontezuela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (377,'ZOAOB','Fortín Acha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (378,'YYMDB','Fortín Olavarría',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (379,'GYAMC','Fortín Tiburcio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (380,'APJZX','Fortín Vigilancia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (381,'DIMIH','Francisco A. Berra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (382,'GUUMW','Francisco Alvarez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (383,'BHYPC','Francisco Ayerza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (384,'POXBY','Francisco Madero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (385,'SQTIQ','Francisco Magnano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (386,'FSCED','Francisco de Victoria',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (387,'ZNXSM','Franklin',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (388,'ROJGU','French',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (389,'QRYAY','Fulton',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (390,'DQGDL','Gahan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (391,'LFATJ','Galo Llorente',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (392,'PCXJN','García del Río',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (393,'IDPVA','Gardey',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (394,'LTEVM','Garin',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (395,'EGOFC','Garré',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (396,'DARPE','General Alvear',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (397,'STRIY','General Arenales',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (398,'MADGY','General Belgrano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (399,'EHSEP','General Conesa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (400,'NWRJA','General Daniel Cerri',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (401,'ECYDY','General Guido',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (402,'DXQWV','General Hornos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (403,'JM3','General Juan Madariaga',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (404,'AKUYU','General La Madrid',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (405,'VNOOT','General Las Heras',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (406,'TZZFG','General Lavalle',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (407,'VZVLK','General Mansilla',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (408,'TKFZS','General OBrien',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (409,'POYRF','General Pacheco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (410,'GWLQI','General Pinto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (411,'YAETE','General Pirán',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (412,'AQYXU','General Rodriguez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (413,'XYEPC','General Rojo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (414,'DVAOI','General Rondeau',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (415,'JDLSZ','General San Martín',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (416,'LNSRX','General Viamonte',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (417,'VGS','General Villega',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (418,'NBYPS','Gerente Cilley',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (419,'HLGAL','Gerli',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (420,'BJFXU','Germania',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (421,'IBVBK','Gil',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (422,'LJRWB','Girodias',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (423,'UJYRE','Girondo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (424,'PCNEJ','Glew',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (425,'GUSUI','Gnecco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (426,'BZKQM','Gobernador Andonaegui',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (427,'LQTOC','Gobernador Arias',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (428,'SYTTP','Gobernador Castro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (429,'RTBBK','Gobernador Monteverde',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (430,'NIKPJ','Gobernador Obligado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (431,'FCBVF','Gobernador Udaondo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (432,'KDXEM','Gobernador Ugarte',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (433,'ARQSS','Goldney',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (434,'IJZJK','Gondra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (435,'PVZOD','Gonzalez Catan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (436,'KBQXB','González Moreno',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (437,'JCZST','González Risos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (438,'GHIRY','Gorchs',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (439,'EUZPP','Gorostiaga',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (440,'SZBXL','Gouin',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (441,'PWVNQ','Gowland',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (442,'EPNYC','Goyena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (443,'DDWDE','Goyeneche',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (444,'NXWDF','Graciarena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (445,'BGHKI','Grand Bourg',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (446,'KPNLV','Gregorio Villafañe',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (447,'IYKRD','Grünbein',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (448,'IRFRM','Guamini',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (449,'PGHLQ','Guanaco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (450,'AZDEY','Guernica',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (451,'CODYF','Guerrero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (452,'FWMEM','Guerrico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (453,'WKLOY','Guido Spano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (454,'ZUSTT','Guillermo E. Hudson',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (455,'QDYES','Gándara',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (456,'YYMVV','Gómez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (457,'UPDRM','Gómez de la Vega',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (458,'QRAIC','Günther',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (459,'UGXWT','Hale',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (460,'IXQSL','Ham',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (461,'WGSVJ','Heavy',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (462,'DZWSA','Henderson',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (463,'FTZIR','Henry Bell',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (464,'KRQZL','Hereford',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (465,'SCACI','Herrera Vegas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (466,'LDAGC','Hilario Ascasubi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (467,'GAZOL','Hinojo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (468,'UPWYB','Hortensia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (469,'TULVL','Huanguelen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (470,'YGZYZ','Hunter',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (471,'YPSVW','Hurlingham',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (472,'EUBHY','Húsares',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (473,'XKDBB','Ibáñez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (474,'MNAYB','Igarzábal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (475,'XCVRA','Ignacio Correas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (476,'IWGKR','Indacochea',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (477,'ARPIL','Indio Rico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (478,'YLSZO','Ingeniero Balbín',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (479,'DDGFU','Ingeniero Beaugey',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (480,'PJFIV','Ingeniero Budge',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (481,'QMLYD','Ingeniero De Madrid',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (482,'CTVKC','Ingeniero J. Allan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (483,'VEHDH','Ingeniero Maschwitz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (484,'BZHTT','Ingeniero Moneta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (485,'AZZSE','Ingeniero Otamendi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (486,'TMCBQ','Ingeniero Silveyra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (487,'ESQXP','Ingeniero Thompson',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (488,'UUWDW','Ingeniero White',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (489,'DVSQY','Ingeniero Williams',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (490,'URTPI','Inocencio Sosa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (491,'VZFNO','Invernadas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (492,'TMOIG','Inés Indart',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (493,'JKGPL','Irala',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (494,'ETYOK','Iraola',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (495,'THWJG','Irene',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (496,'CVWSI','Ireneo Portela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (497,'KLRNN','Iriarte',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (498,'DWNKU','Isidro Casanova',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (499,'TXYTT','Isla Martin Garcia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (500,'TVEGZ','Isla San Pedro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (501,'TZEDH','Isla del Sur',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (502,'GJEVH','Islas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (503,'NWUWB','Islas del Puerto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (504,'GFWMH','Islote del Noroeste',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (505,'YUUZN','Iturreguí',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (506,'BTAJB','Ituzaingo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (507,'YYQJE','J. Caderocco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (508,'HAFVL','Jauregui',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (509,'JCAQJ','Jeppener',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (510,'VLGPK','Joaquín Gorina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (511,'WMCJD','Jose A. Guisasola',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (512,'JCPAZ','Jose C. Paz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (513,'GVPGE','Jose Leon Suarez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (514,'SYMPR','Jose Marmol',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (515,'ZZTHP','José B. Casás',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (516,'TVWCN','José Ferrari',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (517,'QFEPF','José Hernández',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (518,'DKAER','José María Micheo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (519,'HPLXE','José R. Sojo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (520,'TDTAC','José Santos Arévalo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (521,'HSDCL','Juan A. Pradere',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (522,'MTMXC','Juan A. de la Peña',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (523,'ORZUH','Juan Anchorena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (524,'JAXKH','Juan Atucha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (525,'GNILM','Juan Bautista Alberdi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (526,'BVFUD','Juan Blaquier',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (527,'VXRNO','Juan E. Barra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (528,'JLBXS','Juan F. Ibarra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (529,'COUME','Juan Jose Paso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (530,'ZMONV','Juan José Almeyra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (531,'VPFLX','Juan Maria Gutierrez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (532,'QXAOD','Juan N. Fernández',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (533,'AAGYC','Juan Pujol',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (534,'PJQXH','Juan Tronconi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (535,'IGQEY','Juan Vucetich',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (536,'PPLDR','Juancho',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (537,'VSRXX','Julio Arditi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (538,'JNI','Junin',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (539,'ZFTNY','Kenny',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (540,'HIKYQ','Krabbé',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (541,'QPBCD','La Angelita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (542,'AFNPS','La Aurora',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (543,'GYDHH','La Barrancosa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (544,'JXFZB','La Beba',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (545,'NYWKW','La Bolsa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (546,'JZQVP','La Carreta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (547,'IVVQU','La Choza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (548,'BTQBL','La Colina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (549,'PDMHN','La Constancia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (550,'MADKR','La Cotorra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (551,'SIJJI','La Delfina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (552,'MLFYM','La Dorita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (553,'QRVIC','La Dulce',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (554,'QHCQE','La Emilia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (555,'AZFEN','La Estafeta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (556,'SCYAN','La Gloria',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (557,'FVDXJ','La Invencible',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (558,'CQQCM','La Larga',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (559,'ZENBA','La Limpia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (560,'LBICN','La Lucila',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (561,'GBXUH','La Lucila del Mar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (562,'JFDLZ','La Luisa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (563,'UROSR','La Manuela',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (564,'HKHJZ','La Negra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (565,'YTAZI','La Nevada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (566,'UVMOS','La Niña',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (567,'XBNKI','La Noria',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (568,'TLIGM','La Oriental',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (569,'IAZNK','La Pala',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (570,'XHGDZ','La Pastora',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (571,'OXPZE','La Paz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (572,'LOLUH','La Pinta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (573,'LPG','La Plata',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (574,'NZLDO','La Portena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (575,'CWVON','La Primavera',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (576,'PCDLF','La Providencia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (577,'EQUAY','La Reforma',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (578,'ULRPY','La Reja',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (579,'WUVDE','La Rica',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (580,'QTWRS','La Sofía',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (581,'SVHPK','La Sortija',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (582,'IUUNU','La Trinidad',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (583,'MZQJY','La Vanguardia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (584,'QAQIQ','La Verde',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (585,'CGAFQ','La Violeta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (586,'FJNMO','La Virginia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (587,'KXLSB','La Viruta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (588,'RAFON','La Vitícola',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (589,'YQTKB','La Zanja',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (590,'KRJYG','Labardén',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (591,'CXTSO','Laferrere',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (592,'YRKGQ','Lago Epecuen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (593,'FIIMF','Laguna Alsina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (594,'VVNPY','Langueyú',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (595,'WMMTB','Lanus',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (596,'PSKFG','Laplacette',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (597,'EMIDJ','Laprida',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (598,'GRSQA','Larramendy',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (599,'FXWKM','Larrea',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (600,'GPEZH','Lartigau',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (601,'KEYIY','Las Armas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (602,'ELCGF','Las Chacras',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (603,'VWFKP','Las Colinas de Peralta Ramos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (604,'HRABL','Las Flores',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (605,'LG1','Las Gaviotas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (606,'LHS','Las Heras',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (607,'BBQWW','Las Hermanas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (608,'RNGYJ','Las Juanitas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (609,'THYIA','Las Martinetas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (610,'JYIPJ','Las Mostazas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (611,'YRRNY','Las Nutrias',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (612,'JEIMS','Las Palmas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (613,'FWOPJ','Las Parvas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (614,'VBPOM','Las Piedritas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (615,'SOTTW','Las Pipinas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (616,'INVFX','Las Tahonas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (617,'BXBAA','Las Toninas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (618,'LVESU','Las Toscas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (619,'OABEK','Las Vaquerías',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (620,'OPHVG','Lastra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (621,'CDJMM','Lazzarino',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (622,'ASLVX','Leandro N. Alem',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (623,'ZKGIS','Leubucó',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (624,'JBNKA','Libertad',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (625,'GFFFX','Libres del Sur',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (626,'MTMGE','Licenciado Matienzo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (627,'UFRPI','Lima',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (628,'ZSVWM','Lin Calel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (629,'ZBNDX','Lincoln',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (630,'ADJOV','Llavallol',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (631,'FIOUP','Loberia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (632,'TULLG','Lobos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (633,'LOMHE','Loma Hermosa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (634,'GGTWH','Loma Negra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (635,'NHGSQ','Loma Verde',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (636,'CDIKX','Lomas de Zamora',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (637,'GYHGU','Lomas del Mirador',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (638,'CFRZK','Longchamps',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (639,'PLGAV','Los Acantilados',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (640,'CD3','Los Cardales',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (641,'ITQIX','Los Indios',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (642,'ZLDDK','Los Laureles',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (643,'VJLOW','Los Pinos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (644,'FBRDB','Los Polvorines',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (645,'POSBJ','Los Ángeles',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (646,'QTHRO','Louge',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (647,'AVPIZ','Lozano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (648,'YVCVI','Lucas Monteverde',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (649,'RCUUM','Luis Guillon',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (650,'L20','Luján',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (651,'LWGFR','Lumb',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (652,'GHJHA','Luro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (653,'DIRLM','Lynch',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (654,'YKFGB','Lértora',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (655,'PHNLA','Líbano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (656,'QBPCJ','López',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (657,'RIZOU','López Lecube',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (658,'QJCQF','Macedo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (659,'MEVMS','Magdala',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (660,'ADXVH','Magdalena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (661,'AVTSM','Maguire',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (662,'TYAHA','Maipu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (663,'TLBDD','Mamaguita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (664,'MOMCI','Manantiales Chicos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (665,'DGSWJ','Manantiales Grandes',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (666,'IFFPW','Manuel B. Gonnet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (667,'ITLGA','Manuel J. Cobo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (668,'BOZED','Manuel José García',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (669,'QFREL','Manuel Ocampo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (670,'NOHRT','Manzanares',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (671,'ATYZO','Manzone',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (672,'FKMGO','Mapis',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (673,'NUJZM','Maquinista Savio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (674,'MA7','Mar Azul',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (675,'MJ1','Mar de Ajo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (676,'QGCPJ','Mar de Cobo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (677,'MP0','Mar de las Pampas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (678,'MDQ','Mar del Plata',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (679,'M19','Mar del Sur',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (680,'OIOVL','Mar del Tuyu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (681,'UUNWV','Marcos Paz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (682,'LGRRK','Mari Lauquen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (683,'RVCZH','Mariano Acosta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (684,'ZUXUY','Mariano Benítez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (685,'HFZSU','Mariano H. Alfonso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (686,'JPXPG','Mariano J. Haedo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (687,'OSLDP','Mariano Moreno',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (688,'BUEAN','Mariano Roldán',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (689,'ZQDHS','Mariano Unzué',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (690,'YLMSL','Martinez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (691,'KDQHG','Martín Berraondo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (692,'OEUPC','Martín Colman',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (693,'JVHQL','Martín Fierro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (694,'WPDRT','Marucha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (695,'WHBXJ','María Ignacia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (696,'AFFLW','María Lucila',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (697,'GSGYA','Mascota',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (698,'DTABY','Matheu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (699,'NAUOT','Mauricio Hirsch',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (700,'IKWGO','Mayor Buratovich',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (701,'RIBIQ','Maza',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (702,'EFFIR','Mechita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (703,'KCEDR','Mechongué',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (704,'PJZSF','Melchor Romero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (705,'OAPEU','Membrillar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (706,'MDX','Mercedes',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (707,'LTJPH','Merlo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (708,'DMFVZ','Micaela Cascallares',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (709,'IIZON','Ministro Rivadavia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (710,'MNNKV','Mira Pampa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (711,'MJR','Miramar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (712,'NXTZK','Miramonte',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (713,'FJELH','Miranda',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (714,'NUAWT','Moctezuma',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (715,'FHPSY','Moll',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (716,'STXDI','Monasterio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (717,'JMFYS','Mones Cazon',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (718,'SSGKQ','Monroe',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (719,'XXGWB','Monsalvo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (720,'ABCVX','Monte Chingolo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (721,'MNTGD','Monte Grande',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (722,'MH1','Monte Hermoso',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (723,'IILHZ','Monte Veloz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (724,'YMGSJ','Montes de Oca',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (725,'SKUFS','Moores',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (726,'BEKKS','Moquehua',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (727,'FVQER','Morea',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (728,'OWQRR','Moreno',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (729,'DAYGE','Moron',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (730,'HHCXK','Morse',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (731,'WRNTI','Mosconi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (732,'ARQKC','Mouras',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (733,'QEOFD','Mulcahy',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (734,'LZIVM','Muniz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (735,'QJMTD','Munro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (736,'VXWIW','Muñoz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (737,'YJTSQ','Máximo Fernández',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (738,'TGNJE','Máximo Paz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (739,'GWJWQ','Médanos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (740,'WNBTT','Nahuel Rucá',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (741,'BUOBL','Napaleofú',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (742,'IOXJS','Napostá',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (743,'VZTCT','Navarro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (744,'NEC','Necochea',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (745,'VQEQX','Necol',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (746,'AYXNC','Newton',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (747,'NBPTD','Nicanor Olivera',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (748,'JAAXY','Nicolás Descalzi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (749,'MZDEU','Nicolás Levalle',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (750,'WJWWS','Nieves',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (751,'KKZXQ','Norberto de la Riestra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (752,'LOKVV','Nordelta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (753,'NHLOP','Norumbega',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (754,'PPEMJ','Nueva Plata',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (755,'ZEADN','Nueva Roma',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (756,'KRBFE','O. Aballe',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (757,'MHGFT','OHiggins',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (758,'QJGUE','Ochandio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (759,'AXHLV','Olascoaga',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (760,'STBKT','Olavarría',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (761,'LQONG','Oliden',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (762,'ZLXQE','Olivera',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (763,'RIQGA','Olivos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (764,'WNYAM','Ombu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (765,'XPMSM','Ombucta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (766,'KEFQD','Open Door',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (767,'CQQCH','Ordoqui',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (768,'SWXUF','Orense',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (769,'BMWAX','Oriente',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (770,'XCFLR','Ortiz Basualdo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (771,'QRBBP','Ortiz de Rozas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (772,'OS0','Ostende',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (773,'RBZSX','Pablo Acosta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (774,'NGJDQ','Palantelén',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (775,'PEFIR','Palemón Huergo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (776,'KJUOM','Paragüil',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (777,'HCIDF','Paraje El Gavilán',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (778,'QYTCT','Paraje Santa Catalina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (779,'UHBRN','Pardo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (780,'LESRP','Pareje Punta Piedras',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (781,'IOIOF','Parish',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (782,'FHUTI','Parque Camet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (783,'EKRWX','Parravicini',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (784,'ZKEUI','Pasman',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (785,'YEQRD','Paso Mayor',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (786,'DUQUW','Paso del Rey',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (787,'AARSY','Pasteur',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (788,'EMLDL','Patricios',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (789,'QMWHI','Paula',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (790,'IQYTB','Pavon',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (791,'GCFMP','Pazos Kanki',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (792,'WSLVL','Pearson',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (793,'UALQE','Pedernales',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (794,'ROFEA','Pedro Gamen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (795,'VSKAI','Pedro Luro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (796,'BRBRK','Pedro Nicolás Escribano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (797,'LHKDQ','Pedro P. Lasalle',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (798,'JHNKA','Pehuajo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (799,'PEH','Pehuajo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (800,'BUHNO','Pehuelches',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (801,'HAGMK','Pelicurá',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (802,'WPVTF','Pellegrini',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (803,'VWNXS','Peralta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (804,'IBMBV','Peralta Ramos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (805,'CDJPN','Pereyra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (806,'VYQHK','Pergamino',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (807,'AZQRB','Pichincha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (808,'EIPVG','Piedra Echada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (809,'RWUNT','Piedritas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (810,'QOHHH','Pieres',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (811,'JVQJK','Pigue',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (812,'BOVDL','Pila',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (813,'PI5','Pilar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (814,'DQPDM','Pillahuincó',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (815,'PI1','Pinamar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (816,'LJGDX','Pinzón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (817,'MYELL','Pirovano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (818,'YJDGQ','Piñero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (819,'MJXJJ','Piñeyro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (820,'IZHMU','Pla',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (821,'ATKJT','Plaza Montero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (822,'CYHBR','Plomer',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (823,'NUCWA','Plátanos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (824,'ZSETK','Poblet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (825,'WBULR','Polvaredas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (826,'YGMGZ','Pontaut',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (827,'GJKRE','Pontevedra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (828,'JKGNJ','Porvenir',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (829,'MBVUA','Pourtalé',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (830,'LGHDV','Presidente Derqui',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (831,'LYWUR','Presidente Quintana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (832,'XMBXC','Primera Junta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (833,'NVDFB','Puan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (834,'LYCHD','Pueblitos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (835,'YMABE','Pueblo Nuevo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (836,'YOULC','Pueblo San José',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (837,'DNFHZ','Puente Cascallares',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (838,'WNZGA','Puerto Belgrano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (839,'PTQMU','Puerto Cuatreros',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (840,'HDADL','Puerto Galván',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (841,'BXEID','Puerto Quequen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (842,'UTPER','Puerto Rosales',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (843,'GJIMF','Punta Alta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (844,'LNJPM','Punta Chica',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (845,'NLJAN','Punta Indio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (846,'JZLTP','Punta Lara',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (847,'PD1','Punta delgada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (848,'CGLTT','Pérez Millán',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (849,'ZHRMJ','Quenumá',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (850,'DKXIQ','Quequen',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (851,'XPEDU','Quilcó',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (852,'IWUUZ','Quilmes',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (853,'UMJVK','Quintas El Casal',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (854,'RBZNP','Quirno Costa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (855,'KBAUN','Quiroga',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (856,'XDSPL','Quiñihual',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (857,'UOXRF','Rafael Calzada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (858,'DXOJX','Rafael Castillo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (859,'GFXWH','Rafael Obligado',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (860,'RA0','Ramallo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (861,'IMAOG','Ramos Mejia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (862,'XLGLA','Ramos Otero',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (863,'ILLFH','Ramón Biaus',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (864,'XYLSK','Ramón Báez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (865,'ZNRCP','Ramón J. Neild',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (866,'GEIYJ','Ramón Santamarina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (867,'CDKWJ','Rancagua',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (868,'BRDTG','Ranchos',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (869,'RVDCP','Ranelagh',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (870,'AMWKN','Rauch',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (871,'CBXNR','Raulet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (872,'JOHVI','Rawson',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (873,'FXOPR','Real Audiencia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (874,'RUWZV','Recalde',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (875,'HSYSX','Remedios de Escalada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (876,'EMXKD','Reserva',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (877,'EYIOI','Reta',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (878,'EPOYZ','Ricardo Gaviña',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (879,'FTDRP','Ringuelet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (880,'PYMVI','Rio Lujan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (881,'MVCZA','Rio Tala',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (882,'MIQPM','Rivadavia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (883,'JQYUH','Rivadeo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (884,'MVTWM','Rivas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (885,'UCQRC','Rivera',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (886,'PSDRT','Roberto Cano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (887,'HMGRJ','Roberto Payró',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (888,'VIKNN','Roberts',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (889,'YMQDD','Rocha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (890,'ZSRHV','Rojas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (891,'PXXNW','Roosevelt',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (892,'LPKCL','Roque Perez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (893,'YBWJS','Rosas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (894,'UZQDT','Ruiz',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (895,'FRIFN','Saavedra',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (896,'SZQ','Saenz Pena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (897,'DOZLU','Saforcada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (898,'ZQVCD','Saladillo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (899,'AYIRZ','Salazar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (900,'WQJPB','Saldungaray',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (901,'DJPFX','Salliquelo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (902,'GGOQT','Salto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (903,'KUCZV','Salvador María',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (904,'LYNXH','Samborombón',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (905,'QEMFS','San Agustín',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (906,'RPDGP','San Andres de Giles',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (907,'MBCMH','San Andrés',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (908,'SA5','San Antonio de Areco',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (909,'ABOMW','San Antonio de Padua',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (910,'YFCME','San Benito',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (911,'SB1','San Bernardo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (912,'STMQX','San Blas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (913,'YBTFX','San Carlos de Bolivar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (914,'QNQSD','San Cayetano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (915,'ST3','San Clemente del Tuyu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (916,'FUOQS','San Eladio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (917,'QSKCQ','San Emilio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (918,'NUBUU','San Enrique',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (919,'AKTTV','San Fermín',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (920,'SF1','San Fernando',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (921,'PYKSP','San Francisco Solano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (922,'KWVKW','San Francisco de Bellocq',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (923,'ATUFP','San Germán',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (924,'UCQUV','San Ignacio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (925,'SI2','San Isidro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (926,'BLOPE','San Jacinto',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (927,'HMDEG','San Jorge',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (928,'EARJH','San José',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (929,'VZNEU','San Justo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (930,'MLOFZ','San Manuel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (931,'ZWFWB','San Mauricio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (932,'IWRRO','San Mayol',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (933,'ZLTGQ','San Miguel',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (934,'YYTJL','San Miguel del Monte',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (935,'SN3','San Nicolas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (936,'MVJLZ','San Patricio',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (937,'SP1','San Pedro',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (938,'UJAEJ','San Román',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (939,'OHPRX','San Sebastián',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (940,'CJLHA','San Vicente',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (941,'BOYRH','Sansinena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (942,'CVOOI','Santa Catalina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (943,'SSREL','Santa Catalina - Dique Lujan',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (944,'ERYTZ','Santa Clara del Mar',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (945,'ZGDGH','Santa Coloma',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (946,'DCLKV','Santa Elena',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (947,'ZJBUP','Santa Eleodora',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (948,'IYPTK','Santa Inés',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (949,'AJLSE','Santa Lucia',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (950,'IBBUT','Santa Luisa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (951,'ZIPRC','Santa María',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (952,'YELHT','Santa Regina',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (953,'SST','Santa Teresita',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (954,'ITEOX','Santa Trinidad',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (955,'JVULG','Santiago Garbarini',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (956,'WCFKZ','Santiago Larre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (957,'LMJZV','Santo Domingo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (958,'VDRJX','Santo Tomás',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (959,'TJZES','Santos Lugares',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (960,'TSOLQ','Santos Unzué',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (961,'GBUVL','Sarandi',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (962,'EOZYH','Sarasa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (963,'ZJYBU','Saturno',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (964,'XEZLE','Segurola',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (965,'MTDFS','Sevigné',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (966,'AITGY','Shaw',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (967,'FRPDK','Sierra Chica',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (968,'SV1','Sierra de la Ventana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (969,'ETGCC','Sierra de los Padres',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (970,'HPCMH','Sierras Bayas',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (971,'DPXYH','Smith',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (972,'VXNJK','Sol de Mayo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (973,'MCBPQ','Solanet',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (974,'TOCQR','Solano',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (975,'RZZHT','Solís',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (976,'CZPHE','Spurr',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (977,'HKTNW','Stroeder',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (978,'YTSTN','Sucre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (979,'MAWML','Suipacha',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (980,'SFZJZ','Sundblad',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (981,'NUXYG','Sánchez',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (982,'ZZZLZ','Tablada',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (983,'PTTBG','Tacuarí',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (984,'XJBQH','Tamangueyú',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (985,'SSZNP','Tambo Nuevo',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (986,'TDL','Tandil',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (987,'LBZZV','Tapalque',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (988,'LGQDT','Tatay',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (989,'GYJIQ','Tedín Uriburu',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (990,'SLPKT','Tejedor Chico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (991,'WAECU','Temperley',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (992,'OBVUK','Teniente Coronel Miñana',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (993,'QSHTM','Teniente Origone',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (994,'SBRWI','Thames',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (995,'TI5','Tigre',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (996,'GDYXJ','Timote',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (997,'HHXYL','Timote Chico',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (998,'LCEJL','Todd',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (999,'TRRZM','Tolosa',1);
INSERT INTO `cities` (`id`,`code`,`description`,`state_id`) VALUES (1000,'PWBPP','Tomas Jofre',1);
