INSERT INTO `countries` (`id`,`code`,`description`) VALUES (1,'AF','Afganistán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (2,'AL','Albania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (3,'DE','Alemania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (4,'AD','Andorra');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (5,'AO','Angola');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (6,'AI','Anguila');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (7,'AG','Antigua y Barbuda');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (8,'AQ','Antártida');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (9,'SA','Arabia Saudita');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (10,'DZ','Argelia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (11,'AR','Argentina');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (12,'AM','Armenia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (13,'AW','Aruba');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (14,'AU','Australia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (15,'AT','Austria');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (16,'AZ','Azerbaiyán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (17,'BS','Bahamas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (18,'BH','Bahréin');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (19,'BD','Bangladesh');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (20,'BB','Barbados');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (21,'BZ','Belice');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (22,'BJ','Benín');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (23,'BM','Bermudas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (24,'BY','Bielorrusia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (25,'BO','Bolivia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (26,'BA','Bosnia y Herzegovina');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (27,'BW','Botsuana');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (28,'BR','Brasil');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (29,'BN','Brunéi');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (30,'BG','Bulgaria');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (31,'BF','Burkina Faso');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (32,'BI','Burundi');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (33,'BT','Bután');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (34,'BE','Bélgica');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (35,'CV','Cabo Verde');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (36,'KH','Camboya');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (37,'CM','Camerún');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (38,'CA','Canadá');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (39,'TD','Chad');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (40,'CL','Chile');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (41,'CY','Chipre');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (42,'CO','Colombia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (43,'KM','Comoras');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (44,'CG','Congo');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (45,'KP','Corea del Norte');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (46,'KR','Corea del Sur');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (47,'CR','Costa Rica');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (48,'CI','Costa de Marfil');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (49,'HR','Croacia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (50,'CW','Curazao');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (51,'DK','Dinamarca');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (52,'DM','Dominica');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (53,'EC','Ecuador');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (54,'EG','Egipto');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (55,'SV','El Salvador');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (56,'AE','Emiratos Árabes Unidos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (57,'ER','Eritrea');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (58,'SK','Eslovaquia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (59,'SI','Eslovenia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (60,'ES','España');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (61,'FM','Estados Federados de Micronesia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (62,'US','Estados Unidos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (63,'EE','Estonia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (64,'ET','Etiopía');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (65,'PH','Filipinas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (66,'FI','Finlandia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (67,'FJ','Fiyi');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (68,'FR','Francia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (69,'GA','Gabón');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (70,'GM','Gambia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (71,'GE','Georgia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (72,'GH','Ghana');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (73,'GI','Gibraltar');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (74,'GD','Granada');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (75,'GR','Grecia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (76,'GL','Groenlandia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (77,'GP','Guadalupe');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (78,'GU','Guam');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (79,'GT','Guatemala');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (80,'GF','Guayana Francesa');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (81,'GG','Guernsey');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (82,'GN','Guinea');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (83,'GQ','Guinea Ecuatorial');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (84,'GW','Guinea-Bissáu');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (85,'GY','Guyana');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (86,'HT','Haití');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (87,'NL','Holanda');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (88,'HN','Honduras');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (89,'HK','Hong Kong');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (90,'HU','Hungría');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (91,'IN','India');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (92,'ID','Indonesia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (93,'IQ','Iraq');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (94,'IE','Irlanda');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (95,'IR','Irán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (96,'BV','Isla Bouvet');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (97,'CX','Isla Christmas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (98,'NU','Isla Niue');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (99,'NF','Isla Norfolk');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (100,'IM','Isla de Man');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (101,'SX','Isla de San Martín');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (102,'IS','Islandia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (103,'KY','Islas Caimán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (104,'CC','Islas Cocos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (105,'CK','Islas Cook');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (106,'FO','Islas Feroe');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (107,'GS','Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (108,'HM','Islas Heard y McDonald');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (109,'FK','Islas Malvinas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (110,'MP','Islas Marianas del Norte');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (111,'MH','Islas Marshall');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (112,'PN','Islas Pitcairn');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (113,'SB','Islas Salomón');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (114,'TC','Islas Turcas y Caicos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (115,'VG','Islas Vírgenes Británicas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (116,'VI','Islas Vírgenes de los Estados Unidos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (117,'AX','Islas de Åland');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (118,'UM','Islas menores alejadas de los Estados Unidos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (119,'IL','Israel');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (120,'IT','Italia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (121,'JM','Jamaica');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (122,'JP','Japón');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (123,'JE','Jersey');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (124,'JO','Jordania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (125,'KZ','Kazajstán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (126,'KE','Kenia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (127,'KG','Kirguistán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (128,'KI','Kiribati');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (129,'XK','Kosovo');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (130,'KW','Kuwait');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (131,'LA','Laos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (132,'LS','Lesotho');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (133,'LV','Letonia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (134,'LR','Liberia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (135,'LY','Libia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (136,'LI','Liechtenstein');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (137,'LT','Lituania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (138,'LU','Luxemburgo');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (139,'LB','Líbano');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (140,'MO','Macao');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (141,'MK','Macedonia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (142,'MG','Madagascar');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (143,'MY','Malasia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (144,'MW','Malaui');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (145,'MV','Maldivas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (146,'ML','Mali');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (147,'MT','Malta');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (148,'MA','Marruecos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (149,'MQ','Martinica');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (150,'MU','Mauricio');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (151,'MR','Mauritania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (152,'YT','Mayotte');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (153,'MD','Moldavia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (154,'MN','Mongolia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (155,'ME','Montenegro');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (156,'MS','Montserrat');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (157,'MZ','Mozambique');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (158,'BQ','Municipio Especial de Bonaire');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (159,'MM','Myanmar [Birmania]');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (160,'MX','México');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (161,'MC','Mónaco');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (162,'NA','Namibia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (163,'NR','Nauru');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (164,'NP','Nepal');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (165,'NI','Nicaragua');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (166,'NG','Nigeria');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (167,'NO','Noruega');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (168,'NC','Nueva Caledonia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (169,'NZ','Nueva Zelanda');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (170,'NE','Níger');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (171,'OM','Omán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (172,'PK','Pakistán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (173,'PW','Palau');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (174,'PA','Panamá');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (175,'PG','Papúa-Nueva Guinea');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (176,'PY','Paraguay');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (177,'PE','Perú');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (178,'PF','Polinesia Francesa');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (179,'PL','Polonia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (180,'PT','Portugal');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (181,'PR','Puerto Rico');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (182,'QA','Qatar');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (183,'GB','Reino Unido');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (184,'CF','República Centroafricana');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (185,'CZ','República Checa');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (186,'CD','República Democrática del Congo');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (187,'DO','República Dominicana');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (188,'CN','República Popular China');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (189,'SS','República de Sudán del Sur');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (190,'EH','República Árabe Saharaui Democrática');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (191,'RE','Reunión');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (192,'RW','Ruanda');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (193,'RO','Rumanía');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (194,'RU','Rusia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (195,'WS','Samoa');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (196,'AS','Samoa Americana');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (197,'BL','San Bartolomé');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (198,'KN','San Cristóbal y Nieves');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (199,'SM','San Marino');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (200,'MF','San Martín');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (201,'PM','San Pedro y Miquelón');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (202,'VC','San Vicente y las Granadinas');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (203,'SH','Santa Elena');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (204,'LC','Santa Lucía');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (205,'ST','Santo Tomé y Príncipe');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (206,'SN','Senegal');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (207,'RS','Serbia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (208,'SC','Seychelles');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (209,'SL','Sierra Leona');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (210,'SG','Singapur');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (211,'SY','Siria');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (212,'SO','Somalia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (213,'LK','Sri Lanka');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (214,'SZ','Suazilandia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (215,'ZA','Sudáfrica');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (216,'SD','Sudán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (217,'SE','Suecia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (218,'CH','Suiza');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (219,'SR','Surinam');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (220,'SJ','Svalbard y Jan Mayen');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (221,'TH','Tailandia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (222,'TW','Taiwán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (223,'TZ','Tanzania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (224,'TJ','Tayikistán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (225,'IO','Territorio Británico del Océano Índico');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (226,'TF','Territorios Australes Franceses');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (227,'PS','Territorios Palestinos');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (228,'TL','Timor Oriental');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (229,'TG','Togo');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (230,'TK','Tokelau');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (231,'TO','Tonga');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (232,'TT','Trinidad y Tobago');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (233,'TM','Turkmenistán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (234,'TR','Turquía');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (235,'TV','Tuvalu');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (236,'TN','Túnez');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (237,'UA','Ucrania');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (238,'UG','Uganda');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (239,'UY','Uruguay');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (240,'UZ','Uzbekistán');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (241,'VU','Vanuatu');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (242,'VE','Venezuela');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (243,'VN','Vietnam');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (244,'WF','Wallis y Futuna');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (245,'YE','Yemen');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (246,'DJ','Yibuti');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (247,'ZM','Zambia');
INSERT INTO `countries` (`id`,`code`,`description`) VALUES (248,'ZW','Zimbawe');