/*
-- Query: SELECT * FROM singuia.countries
LIMIT 0, 1000

-- Date: 2014-09-02 12:17
*/
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (1,'AF','Afganistán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (2,'AL','Albania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (3,'DE','Alemania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (4,'AD','Andorra',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (5,'AO','Angola',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (6,'AI','Anguila',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (7,'AG','Antigua y Barbuda',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (8,'AQ','Antártida',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (9,'SA','Arabia Saudita',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (10,'DZ','Argelia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (11,'AR','Argentina','1');
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (12,'AM','Armenia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (13,'AW','Aruba',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (14,'AU','Australia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (15,'AT','Austria',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (16,'AZ','Azerbaiyán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (17,'BS','Bahamas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (18,'BH','Bahréin',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (19,'BD','Bangladesh',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (20,'BB','Barbados',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (21,'BZ','Belice',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (22,'BJ','Benín',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (23,'BM','Bermudas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (24,'BY','Bielorrusia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (25,'BO','Bolivia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (26,'BA','Bosnia y Herzegovina',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (27,'BW','Botsuana',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (28,'BR','Brasil',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (29,'BN','Brunéi',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (30,'BG','Bulgaria',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (31,'BF','Burkina Faso',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (32,'BI','Burundi',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (33,'BT','Bután',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (34,'BE','Bélgica',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (35,'CV','Cabo Verde',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (36,'KH','Camboya',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (37,'CM','Camerún',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (38,'CA','Canadá',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (39,'TD','Chad',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (40,'CL','Chile',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (41,'CY','Chipre',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (42,'CO','Colombia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (43,'KM','Comoras',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (44,'CG','Congo',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (45,'KP','Corea del Norte',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (46,'KR','Corea del Sur',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (47,'CR','Costa Rica',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (48,'CI','Costa de Marfil',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (49,'HR','Croacia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (50,'CW','Curazao',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (51,'DK','Dinamarca',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (52,'DM','Dominica',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (53,'EC','Ecuador',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (54,'EG','Egipto',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (55,'SV','El Salvador',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (56,'AE','Emiratos Árabes Unidos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (57,'ER','Eritrea',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (58,'SK','Eslovaquia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (59,'SI','Eslovenia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (60,'ES','España',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (61,'FM','Estados Federados de Micronesia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (62,'US','Estados Unidos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (63,'EE','Estonia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (64,'ET','Etiopía',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (65,'PH','Filipinas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (66,'FI','Finlandia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (67,'FJ','Fiyi',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (68,'FR','Francia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (69,'GA','Gabón',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (70,'GM','Gambia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (71,'GE','Georgia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (72,'GH','Ghana',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (73,'GI','Gibraltar',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (74,'GD','Granada',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (75,'GR','Grecia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (76,'GL','Groenlandia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (77,'GP','Guadalupe',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (78,'GU','Guam',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (79,'GT','Guatemala',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (80,'GF','Guayana Francesa',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (81,'GG','Guernsey',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (82,'GN','Guinea',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (83,'GQ','Guinea Ecuatorial',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (84,'GW','Guinea-Bissáu',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (85,'GY','Guyana',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (86,'HT','Haití',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (87,'NL','Holanda',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (88,'HN','Honduras',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (89,'HK','Hong Kong',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (90,'HU','Hungría',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (91,'IN','India',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (92,'ID','Indonesia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (93,'IQ','Iraq',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (94,'IE','Irlanda',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (95,'IR','Irán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (96,'BV','Isla Bouvet',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (97,'CX','Isla Christmas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (98,'NU','Isla Niue',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (99,'NF','Isla Norfolk',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (100,'IM','Isla de Man',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (101,'SX','Isla de San Martín',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (102,'IS','Islandia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (103,'KY','Islas Caimán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (104,'CC','Islas Cocos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (105,'CK','Islas Cook',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (106,'FO','Islas Feroe',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (107,'GS','Islas Georgia del Sur y Sandwich del Sur',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (108,'HM','Islas Heard y McDonald',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (109,'FK','Islas Malvinas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (110,'MP','Islas Marianas del Norte',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (111,'MH','Islas Marshall',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (112,'PN','Islas Pitcairn',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (113,'SB','Islas Salomón',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (114,'TC','Islas Turcas y Caicos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (115,'VG','Islas Vírgenes Británicas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (116,'VI','Islas Vírgenes de los Estados Unidos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (117,'AX','Islas de Åland',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (118,'UM','Islas menores alejadas de los Estados Unidos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (119,'IL','Israel',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (120,'IT','Italia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (121,'JM','Jamaica',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (122,'JP','Japón',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (123,'JE','Jersey',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (124,'JO','Jordania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (125,'KZ','Kazajstán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (126,'KE','Kenia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (127,'KG','Kirguistán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (128,'KI','Kiribati',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (129,'XK','Kosovo',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (130,'KW','Kuwait',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (131,'LA','Laos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (132,'LS','Lesotho',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (133,'LV','Letonia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (134,'LR','Liberia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (135,'LY','Libia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (136,'LI','Liechtenstein',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (137,'LT','Lituania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (138,'LU','Luxemburgo',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (139,'LB','Líbano',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (140,'MO','Macao',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (141,'MK','Macedonia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (142,'MG','Madagascar',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (143,'MY','Malasia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (144,'MW','Malaui',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (145,'MV','Maldivas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (146,'ML','Mali',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (147,'MT','Malta',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (148,'MA','Marruecos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (149,'MQ','Martinica',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (150,'MU','Mauricio',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (151,'MR','Mauritania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (152,'YT','Mayotte',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (153,'MD','Moldavia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (154,'MN','Mongolia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (155,'ME','Montenegro',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (156,'MS','Montserrat',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (157,'MZ','Mozambique',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (158,'BQ','Municipio Especial de Bonaire',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (159,'MM','Myanmar [Birmania]',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (160,'MX','México',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (161,'MC','Mónaco',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (162,'NA','Namibia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (163,'NR','Nauru',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (164,'NP','Nepal',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (165,'NI','Nicaragua',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (166,'NG','Nigeria',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (167,'NO','Noruega',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (168,'NC','Nueva Caledonia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (169,'NZ','Nueva Zelanda',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (170,'NE','Níger',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (171,'OM','Omán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (172,'PK','Pakistán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (173,'PW','Palau',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (174,'PA','Panamá',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (175,'PG','Papúa-Nueva Guinea',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (176,'PY','Paraguay',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (177,'PE','Perú',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (178,'PF','Polinesia Francesa',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (179,'PL','Polonia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (180,'PT','Portugal',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (181,'PR','Puerto Rico',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (182,'QA','Qatar',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (183,'GB','Reino Unido',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (184,'CF','República Centroafricana',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (185,'CZ','República Checa',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (186,'CD','República Democrática del Congo',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (187,'DO','República Dominicana',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (188,'CN','República Popular China',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (189,'SS','República de Sudán del Sur',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (190,'EH','República Árabe Saharaui Democrática',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (191,'RE','Reunión',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (192,'RW','Ruanda',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (193,'RO','Rumanía',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (194,'RU','Rusia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (195,'WS','Samoa',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (196,'AS','Samoa Americana',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (197,'BL','San Bartolomé',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (198,'KN','San Cristóbal y Nieves',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (199,'SM','San Marino',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (200,'MF','San Martín',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (201,'PM','San Pedro y Miquelón',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (202,'VC','San Vicente y las Granadinas',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (203,'SH','Santa Elena',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (204,'LC','Santa Lucía',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (205,'ST','Santo Tomé y Príncipe',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (206,'SN','Senegal',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (207,'RS','Serbia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (208,'SC','Seychelles',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (209,'SL','Sierra Leona',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (210,'SG','Singapur',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (211,'SY','Siria',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (212,'SO','Somalia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (213,'LK','Sri Lanka',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (214,'SZ','Suazilandia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (215,'ZA','Sudáfrica',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (216,'SD','Sudán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (217,'SE','Suecia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (218,'CH','Suiza',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (219,'SR','Surinam',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (220,'SJ','Svalbard y Jan Mayen',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (221,'TH','Tailandia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (222,'TW','Taiwán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (223,'TZ','Tanzania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (224,'TJ','Tayikistán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (225,'IO','Territorio Británico del Océano Índico',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (226,'TF','Territorios Australes Franceses',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (227,'PS','Territorios Palestinos',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (228,'TL','Timor Oriental',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (229,'TG','Togo',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (230,'TK','Tokelau',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (231,'TO','Tonga',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (232,'TT','Trinidad y Tobago',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (233,'TM','Turkmenistán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (234,'TR','Turquía',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (235,'TV','Tuvalu',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (236,'TN','Túnez',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (237,'UA','Ucrania',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (238,'UG','Uganda',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (239,'UY','Uruguay',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (240,'UZ','Uzbekistán',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (241,'VU','Vanuatu',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (242,'VE','Venezuela',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (243,'VN','Vietnam',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (244,'WF','Wallis y Futuna',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (245,'YE','Yemen',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (246,'DJ','Yibuti',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (247,'ZM','Zambia',0);
INSERT INTO `countries` (`id`,`code`,`description`,`is_enabled`) VALUES (248,'ZW','Zimbawe',0);
