INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (1,'AR-B','Buenos Aires',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (2,'AR-K','Catamarca',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (3,'AR-H','Chaco',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (4,'AR-U','Chubut',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (5,'AR-C','Ciudad de Buenos Aires',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (6,'AR-X','Córdoba',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (7,'AR-W','Corrientes',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (8,'AR-E','Entre Ríos',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (9,'AR-P','Formosa',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (10,'AR-Y','Jujuy',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (11,'AR-L','La Pampa',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (12,'AR-F','La Rioja',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (13,'AR-M','Mendoza',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (14,'AR-N','Misiones',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (15,'AR-Q','Neuquén',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (16,'AR-R','Río Negro',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (17,'AR-A','Salta',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (18,'AR-J','San Juan',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (19,'AR-D','San Luis',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (20,'AR-Z','Santa Cruz',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (21,'AR-S','Santa Fe',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (22,'AR-G','Santiago del Estero',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (23,'AR-V','Tierra del Fuego',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (24,'AR-T','Tucumán',11);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (25,'BO','l Beni',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (26,'BO','Chuquisaca',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (27,'BO','Cochabamba',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (28,'BO','La Paz',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (29,'BO','Oruro',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (30,'BO','Pando',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (31,'BO','Potosí',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (32,'BO','Santa Cruz',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (33,'BO','Tarija',25);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (34,'BR-AC','Acre',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (35,'BR-AL','Alagoas',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (36,'BR-AP','Amapá',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (37,'BR-AM','Amazonas',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (38,'BR-BA','Bahia',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (39,'BR-CE','Ceará',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (40,'BR-DF','Distrito Federal',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (41,'BR-ES','Espírito Santo',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (42,'BR-GO','Goiás',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (43,'BR-MA','Maranhão',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (44,'BR-MT','Mato Grosso',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (45,'BR-MS','Mato Grosso do Sul',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (46,'BR-MG','Minas Gerais',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (47,'BR-PA','Pará',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (48,'BR-PB','Paraíba',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (49,'BR-PR','Parana',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (50,'BR-PE','Pernambuco',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (51,'BR-PI','Piauí',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (52,'BR-RJ','Rio de Janeiro',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (53,'BR-RN','Rio Grande do Norte',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (54,'BR-RS','Rio Grande do Sul',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (55,'BR-RO','Rondônia',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (56,'BR-RR','Roraima',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (57,'BR-SC','Santa Catarina',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (58,'BR-SP','San Pablo',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (59,'BR-SE','Sergipe',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (60,'BR-TO','Tocantins',28);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (61,'CA-AB','Alberta',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (62,'CA-BC','Columbia Británica',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (63,'CA-PE','Isla del Príncipe Eduardo',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (64,'CA-MB','Manitoba',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (65,'CA-NT','North West Territories',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (66,'CA-NB','Nuevo Brunswick',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (67,'CA-NS','Nueva Escocia',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (68,'CA-NU','Nunavut',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (69,'CA-ON','Ontario',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (70,'CA-QC','Quebec',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (71,'CA-SK','Saskatchewan',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (72,'CA-NL','Terranova y Labrador',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (73,'CA-YT','Yukon',38);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (74,'CL','Antofagasta',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (75,'CL','Araucanía',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (76,'CL','Arica y Parinacota',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (77,'CL','Atacama',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (78,'CL','Aysén',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (79,'CL','Biobío',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (80,'CL','Coquimbo',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (81,'CL','Libertador General Bernardo O\'Higgins',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (82,'CL','Los Ríos',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (83,'CL','Magallanes',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (84,'CL','Maule',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (85,'CL','Valparaíso',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (86,'CL','Los Lagos',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (87,'CL','Santiago',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (88,'CL','Tarapacá',40);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (89,'CO-AMA','Amazonas',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (90,'CO-ANT','Antioquia',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (91,'CO-ARA','Arauca',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (92,'CO-ATL','Atlántico',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (93,'CO-DC','Bogotá D.C.',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (94,'CO-BOL','Bolívar',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (95,'CO-BOY','Boyacá',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (96,'CO-CAL','Caldas',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (97,'CO-CAQ','Caquetá',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (98,'CO-CAS','Casanare',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (99,'CO-CAU','Cauca',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (100,'CO-CES','Cesar',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (101,'CO-CHO','Chocó',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (102,'CO-COR','Córdoba',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (103,'CO-CUN','Cundinamarca',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (104,'CO-GUA','Guainía',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (105,'CO-GUV','Guaviare',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (106,'CO-HUI','Huila',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (107,'CO-LAG','La Guajira',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (108,'CO-MAG','Magdalena',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (109,'CO-MET','Meta',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (110,'CO-NAR','Nariño',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (111,'CO-NSA','Norte de Santander',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (112,'CO-SAP','Providencia y Santa Catalina, Archipiélago de San Andrés',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (113,'CO-PUT','Putumayo',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (114,'CO-QUI','Quindío',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (115,'CO-RIS','Risaralda',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (116,'CO-SAN','Santander',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (117,'CO-SUC','Sucre',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (118,'CO-TOL','Tolima',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (119,'CO-VAC','Valle del Cauca',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (120,'CO-VAU','Vaupés',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (121,'CO-VID','Vichada',42);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (122,'CR','Alajuela',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (123,'CR','Cartago',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (124,'CR','Guanacaste',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (125,'CR','Heredia',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (126,'CR','Limon',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (127,'CR','Puntarenas',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (128,'CR','San Jose',47);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (129,'EC','Azuay',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (130,'EC','Bolivar',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (131,'EC','Canar',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (132,'EC','Carchi',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (133,'EC','Chimborazo',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (134,'EC','Cotopaxi',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (135,'EC','El Oro',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (136,'EC','Esmeraldas',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (137,'EC','Francisco de Orellana',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (138,'EC','Galápagos',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (139,'EC','Guayas',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (140,'EC','Imbabura',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (141,'EC','Loja',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (142,'EC','Los Rios',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (143,'EC','Manabí',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (144,'EC','Morona Santiago',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (145,'EC','Napo',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (146,'EC','Pastaza',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (147,'EC','Pichincha',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (148,'EC','Santa Elena',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (149,'EC','Santo Domingo de los Tsachilas',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (150,'EC','Sucumbios',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (151,'EC','Tungurahua',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (152,'EC','Zamora Chinchipe',53);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (153,'SV','Ahuachapan',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (154,'SV','Cabanas',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (155,'SV','Chalatenango',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (156,'SV','Cuscatlan',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (157,'SV','La Libertad',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (158,'SV','La Paz',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (159,'SV','La Union',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (160,'SV','Morazan',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (161,'SV','San Miguel',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (162,'SV','San Salvador',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (163,'SV','San Vicente',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (164,'SV','Santa Ana',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (165,'SV','Sonsonate',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (166,'SV','Usulutan',55);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (167,'ES','Galicia',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (168,'ES','Andalucía',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (169,'ES','Aragón',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (170,'ES','Canarias',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (171,'ES','Cantabria',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (172,'ES','Castilla y León',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (173,'ES','Castilla-La Mancha',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (174,'ES','Cataluña',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (175,'ES','Ciudad de Ceuta',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (176,'ES','Comunidad de Madrid',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (177,'ES','Comunidad valenciana',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (178,'ES','País Vasco',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (179,'ES','Extremadura',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (180,'ES','Illes Balears',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (181,'ES','La Rioja',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (182,'ES','Melilla',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (183,'ES','Navarra',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (184,'ES','Asturias',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (185,'ES','Murcia',60);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (186,'US-AL','Alabama',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (187,'US-AK','Alaska',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (188,'US-AR','Arkansas',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (189,'US-AZ','Arizona',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (190,'US-CA','California',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (191,'US-NC','Carolina del Norte',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (192,'US-SC','Carolina del Sur',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (193,'US-CO','Colorado',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (194,'US-DC','Columbia',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (195,'US-CT','Connecticut',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (196,'US-ND','Dakota del Norte',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (197,'US-SD','Dakota del Sur',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (198,'US-DE','Delaware',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (199,'US-FL','Florida',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (200,'US-GA','Georgia',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (201,'US-HI','Hawaii',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (202,'US-ID','Idaho',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (203,'US-RI','Rhode Island',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (204,'US-IL','Illinois',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (205,'US-IN','Indiana',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (206,'US-IA','Iowa',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (207,'US-KS','Kansas',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (208,'US-KY','Kentucky',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (209,'US-LA','Louisiana',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (210,'US-ME','Maine',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (211,'US-MD','Maryland',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (212,'US-MA','Massachusetts',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (213,'US-MI','Michigan',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (214,'US-MN','Minnesota',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (215,'US-MS','Mississippi',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (216,'US-MO','Missouri',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (217,'US-MT','Montana',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (218,'US-NE','Nebraska',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (219,'US-NV','Nevada',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (220,'US-NH','Nueva Hampshire',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (221,'US-NY','Nueva York',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (222,'US-NJ','Nueva Jersey',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (223,'US-NM','Nuevo México',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (224,'US-OK','Oklahoma',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (225,'US-OH','Ohio',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (226,'US-OR','Oregón',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (227,'US-PA','Pensilvania',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (228,'US-TN','Tennessee',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (229,'US-TX','Texas',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (230,'US-UT','Utah',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (231,'US-VT','Vermont',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (232,'US-VA','Virginia',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (233,'US-WV','Virginia Occidental',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (234,'US-WA','Washington',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (235,'US-WI','Wisconsin',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (236,'US-WY','Wyoming',62);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (237,'GT','Alta Verapaz',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (238,'GT','Baja Verapaz',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (239,'GT','Chimaltenango',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (240,'GT','Chiquimula',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (241,'GT','El Progreso',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (242,'GT','Escuintla',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (243,'GT','Guatemala',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (244,'GT','Huehuetenango',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (245,'GT','Izabal',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (246,'GT','Jalapa',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (247,'GT','Jutiapa',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (248,'GT','Peten',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (249,'GT','Quetzaltenango',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (250,'GT','Quiche',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (251,'GT','Retalhuleu',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (252,'GT','Sacatepequez',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (253,'GT','San Marcos',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (254,'GT','Santa Rosa',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (255,'GT','Solola',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (256,'GT','Suchitepequez',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (257,'GT','Totonicapan',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (258,'GT','Zacapa',79);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (259,'HN','Atlantida',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (260,'HN','Choluteca',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (261,'HN','Colon',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (262,'HN','Comayagua',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (263,'HN','Copan',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (264,'HN','Cortés',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (265,'HN','El Paraiso',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (266,'HN','Francisco Morazán',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (267,'HN','Gracias a Dios',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (268,'HN','Intibuca',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (269,'HN','Islas de la Bahía',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (270,'HN','La Paz',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (271,'HN','Lempira',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (272,'HN','Ocotepeque',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (273,'HN','Olancho',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (274,'HN','Santa Barbara',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (275,'HN','Valle',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (276,'HN','Yoro',88);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (277,'MX-AGU','Aguascalientes',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (278,'MX-BCS','Baja California Sur',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (279,'MX-BCN','Baja California',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (280,'MX-CAM','Campeche',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (281,'MX-CHP','Chiapas',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (282,'MX-CHH','Chihuahua',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (283,'MX-COA','Coahuila de Zaragoza',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (284,'MX-COL','Colima',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (285,'MX-DUR','Durango',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (286,'MX-GUA','Guanajuato',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (287,'MX-GRO','Guerrero',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (288,'MX-HID','Hidalgo',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (289,'MX-JAL','Jalisco',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (290,'MX-MEX','México',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (291,'MX-DIF','México D.F.',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (292,'MX-MIC','Michoacán de Ocampo',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (293,'MX-MOR','Morelos',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (294,'MX-NAY','Nayarit',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (295,'MX-NLE','Nuevo León',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (296,'MX-OAX','Oaxaca',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (297,'MX-PUE','Puebla',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (298,'MX-QUE','Querétaro Arteaga',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (299,'MX-ROO','Quintana Roo',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (300,'MX-SLP','San Luis Potosí',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (301,'MX-SIN','Sinaloa',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (302,'MX-SON','Sonora',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (303,'MX-TAB','Tabasco',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (304,'MX-TAM','Tamaulipas',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (305,'MX-TLA','Tlaxcala',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (306,'MX-VER','Veracruz-Llave',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (307,'MX-YUC','Yucatán',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (308,'MX-ZAC','Zacatecas',160);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (309,'NI','Boaco',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (310,'NI','Carazo',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (311,'NI','Chinandega',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (312,'NI','Chontales',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (313,'NI','Esteli',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (314,'NI','Granada',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (315,'NI','Jinotega',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (316,'NI','Leon',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (317,'NI','Madriz',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (318,'NI','Managua',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (319,'NI','Masaya',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (320,'NI','Matagalpa',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (321,'NI','Nueva Segovia',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (322,'NI','Region Autonoma Atlantico Norte',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (323,'NI','Region Autonoma Atlantico Sur',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (324,'NI','Rio San Juan',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (325,'NI','Rivas',165);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (326,'PA','Bocas del Toro',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (327,'PA','Chiriqui',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (328,'PA','Cocle',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (329,'PA','Colón',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (330,'PA','Darien',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (331,'PA','Embera-Wounaan',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (332,'PA','Herrera',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (333,'PA','San Blas',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (334,'PA','Los Santos',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (335,'PA','Ngoebe-Bugle',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (336,'PA','Panamá',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (337,'PA','Veraguas',174);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (338,'PY','Alto Paraguay',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (339,'PY','Alto Parana',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (340,'PY','Amambay',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (341,'PY','Asuncion',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (342,'PY','Boqueron',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (343,'PY','Caaguazu',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (344,'PY','Caazapa',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (345,'PY','Canindeyu',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (346,'PY','Central',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (347,'PY','Concepcion',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (348,'PY','Itapua',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (349,'PY','l Guaira',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (350,'PY','la Cordillera',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (351,'PY','Misiones',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (352,'PY','Neembucu',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (353,'PY','Paraguari',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (354,'PY','Presidente Hayes',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (355,'PY','San Pedro',176);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (356,'PE-AMA','Amazonas',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (357,'PE-ANC','Ancash',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (358,'PE-APU','Apurimac',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (359,'PE-ARE','Arequipa',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (360,'PE-AYA','Ayacucho',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (361,'PE-CAJ','Cajamarca',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (362,'PE-CAL','Callao',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (363,'PE-CUS','Cusco',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (364,'PE-HUV','Huancavelica',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (365,'PE-ICA','Ica',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (366,'PE-JUN','Junin',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (367,'PE-LAL','La Libertad',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (368,'PE-LAM','Lambayeque',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (369,'PE-LIM','Lima',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (370,'PE-LMA','Lima',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (371,'PE-LOR','Loreto',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (372,'PE-MDD','Madre de Dios',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (373,'PE-MOR','Moquegua',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (374,'PE-PAS','Pasco',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (375,'PE-PIU','Piura',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (376,'PE-PUN','Puno',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (377,'PE-HUC','Region de Huanuco',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (378,'PE-SAM','San Martín',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (379,'PE-TAC','Tacna',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (380,'PE-TUM','Tumbes',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (381,'PE-UCA','Ucayali',177);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (382,'PR','Adjuntas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (383,'PR','Aguada',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (384,'PR','Aguadilla',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (385,'PR','Aguas Buenas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (386,'PR','Aibonito',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (387,'PR','Anasco',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (388,'PR','Arecibo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (389,'PR','Arroyo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (390,'PR','Barceloneta',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (391,'PR','Barranquitas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (392,'PR','Bayamon',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (393,'PR','Cabo Rojo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (394,'PR','Caguas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (395,'PR','Camuy',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (396,'PR','Canovanas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (397,'PR','Carolina',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (398,'PR','Catano',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (399,'PR','Cayey',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (400,'PR','Ceiba',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (401,'PR','Ciales',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (402,'PR','Cidra',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (403,'PR','Coamo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (404,'PR','Comerio',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (405,'PR','Corozal',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (406,'PR','Culebra',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (407,'PR','Dorado',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (408,'PR','Fajardo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (409,'PR','Florida',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (410,'PR','Guanica',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (411,'PR','Guayama',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (412,'PR','Guayanilla',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (413,'PR','Guaynabo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (414,'PR','Gurabo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (415,'PR','Hatillo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (416,'PR','Hormigueros',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (417,'PR','Humacao',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (418,'PR','Isabela',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (419,'PR','Jayuya',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (420,'PR','Juana Diaz',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (421,'PR','Juncos',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (422,'PR','Lajas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (423,'PR','Lares',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (424,'PR','Las Marias',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (425,'PR','Las Piedras',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (426,'PR','Loiza',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (427,'PR','Luquillo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (428,'PR','Manati',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (429,'PR','Maricao',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (430,'PR','Maunabo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (431,'PR','Mayagueez',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (432,'PR','Moca',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (433,'PR','Morovis',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (434,'PR','Naguabo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (435,'PR','Naranjito',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (436,'PR','Orocovis',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (437,'PR','Patillas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (438,'PR','Penuelas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (439,'PR','Ponce',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (440,'PR','Quebradillas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (441,'PR','Rincon',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (442,'PR','Rio Grande',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (443,'PR','Sabana Grande',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (444,'PR','Salinas',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (445,'PR','San German',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (446,'PR','San Juan',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (447,'PR','San Lorenzo',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (448,'PR','San Sebastian',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (449,'PR','Santa Isabel',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (450,'PR','Toa Alta',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (451,'PR','Toa Baja',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (452,'PR','Trujillo Alto',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (453,'PR','Utuado',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (454,'PR','Vega Alta',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (455,'PR','Vega Baja',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (456,'PR','Vieques',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (457,'PR','Villalba',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (458,'PR','Yabucoa',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (459,'PR','Yauco',181);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (460,'DO','Azua',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (461,'DO','Baoruco',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (462,'DO','Barahona',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (463,'DO','Dajabon',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (464,'DO','Distrito Nacional',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (465,'DO','Duarte',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (466,'DO','El Seibo',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (467,'DO','Elias Pina',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (468,'DO','Espaillat',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (469,'DO','Hato Mayor',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (470,'DO','Hermanas Mirabal',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (471,'DO','Independencia',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (472,'DO','La Altagracia',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (473,'DO','La Romana',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (474,'DO','La Vega',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (475,'DO','Maria Trinidad Sanchez',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (476,'DO','Monsenor Nouel',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (477,'DO','Monte Cristi',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (478,'DO','Monte Plata',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (479,'DO','Pedernales',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (480,'DO','Peravia',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (481,'DO','Puerto Plata',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (482,'DO','Samana',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (483,'DO','San Cristobal',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (484,'DO','San Jose de Ocoa',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (485,'DO','San Juan',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (486,'DO','San Pedro de Macoris',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (487,'DO','Sanchez Ramirez',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (488,'DO','Santiago',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (489,'DO','Santiago Rodriguez',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (490,'DO','Santo Domingo',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (491,'DO','Valverde',187);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (492,'UY','Canelones',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (493,'UY','Colonia',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (494,'UY','Artigas',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (495,'UY','Cerro Largo',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (496,'UY','Florida',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (497,'UY','Durazno',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (498,'UY','Flores',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (499,'UY','Lavalleja',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (500,'UY','Maldonado',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (501,'UY','Montevideo',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (502,'UY','Paysandu',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (503,'UY','Rio Negro',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (504,'UY','Rivera',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (505,'UY','Rocha',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (506,'UY','Salto',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (507,'UY','San Jose',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (508,'UY','Soriano',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (509,'UY','Tacuarembo',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (510,'UY','Treinta y Tres',239);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (511,'VE','Anzoátegui',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (512,'VE','Aragua',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (513,'VE','Barinas',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (514,'VE','Bolívar',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (515,'VE','Carabobo',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (516,'VE','Caracas',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (517,'VE','Delta Amacuro',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (518,'VE','Dependencias Federales',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (519,'VE','Apure',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (520,'VE','Cojedes',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (521,'VE','Coro',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (522,'VE','Guárico',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (523,'VE','Portuguesa',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (524,'VE','Cumaná',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (525,'VE','Táchira',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (526,'VE','Estado Trujillo',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (527,'VE','Estado Vargas',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (528,'VE','Yaracuy',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (529,'VE','Lara',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (530,'VE','Mérida',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (531,'VE','Miranda',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (532,'VE','Monagas',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (533,'VE','Nueva Esparta',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (534,'VE','Amazonas',242);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`) VALUES (535,'VE','Zulia',242);
