/*
-- Query: SELECT * FROM singuia.states
LIMIT 0, 1000

-- Date: 2014-09-02 12:17
*/
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (1,'AR-B','Buenos Aires',11,1);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (2,'AR-K','Catamarca',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (3,'AR-H','Chaco',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (4,'AR-U','Chubut',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (5,'AR-C','Ciudad de Buenos Aires',11,1);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (6,'AR-X','Córdoba',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (7,'AR-W','Corrientes',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (8,'AR-E','Entre Ríos',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (9,'AR-P','Formosa',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (10,'AR-Y','Jujuy',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (11,'AR-L','La Pampa',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (12,'AR-F','La Rioja',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (13,'AR-M','Mendoza',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (14,'AR-N','Misiones',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (15,'AR-Q','Neuquén',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (16,'AR-R','Río Negro',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (17,'AR-A','Salta',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (18,'AR-J','San Juan',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (19,'AR-D','San Luis',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (20,'AR-Z','Santa Cruz',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (21,'AR-S','Santa Fe',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (22,'AR-G','Santiago del Estero',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (23,'AR-V','Tierra del Fuego',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (24,'AR-T','Tucumán',11,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (25,'BO','l Beni',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (26,'BO','Chuquisaca',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (27,'BO','Cochabamba',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (28,'BO','La Paz',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (29,'BO','Oruro',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (30,'BO','Pando',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (31,'BO','Potosí',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (32,'BO','Santa Cruz',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (33,'BO','Tarija',25,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (34,'BR-AC','Acre',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (35,'BR-AL','Alagoas',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (36,'BR-AP','Amapá',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (37,'BR-AM','Amazonas',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (38,'BR-BA','Bahia',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (39,'BR-CE','Ceará',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (40,'BR-DF','Distrito Federal',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (41,'BR-ES','Espírito Santo',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (42,'BR-GO','Goiás',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (43,'BR-MA','Maranhão',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (44,'BR-MT','Mato Grosso',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (45,'BR-MS','Mato Grosso do Sul',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (46,'BR-MG','Minas Gerais',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (47,'BR-PA','Pará',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (48,'BR-PB','Paraíba',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (49,'BR-PR','Parana',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (50,'BR-PE','Pernambuco',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (51,'BR-PI','Piauí',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (52,'BR-RJ','Rio de Janeiro',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (53,'BR-RN','Rio Grande do Norte',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (54,'BR-RS','Rio Grande do Sul',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (55,'BR-RO','Rondônia',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (56,'BR-RR','Roraima',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (57,'BR-SC','Santa Catarina',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (58,'BR-SP','San Pablo',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (59,'BR-SE','Sergipe',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (60,'BR-TO','Tocantins',28,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (61,'CA-AB','Alberta',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (62,'CA-BC','Columbia Británica',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (63,'CA-PE','Isla del Príncipe Eduardo',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (64,'CA-MB','Manitoba',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (65,'CA-NT','North West Territories',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (66,'CA-NB','Nuevo Brunswick',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (67,'CA-NS','Nueva Escocia',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (68,'CA-NU','Nunavut',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (69,'CA-ON','Ontario',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (70,'CA-QC','Quebec',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (71,'CA-SK','Saskatchewan',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (72,'CA-NL','Terranova y Labrador',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (73,'CA-YT','Yukon',38,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (74,'CL','Antofagasta',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (75,'CL','Araucanía',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (76,'CL','Arica y Parinacota',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (77,'CL','Atacama',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (78,'CL','Aysén',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (79,'CL','Biobío',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (80,'CL','Coquimbo',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (81,'CL','Libertador General Bernardo O''Higgins',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (82,'CL','Los Ríos',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (83,'CL','Magallanes',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (84,'CL','Maule',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (85,'CL','Valparaíso',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (86,'CL','Los Lagos',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (87,'CL','Santiago',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (88,'CL','Tarapacá',40,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (89,'CO-AMA','Amazonas',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (90,'CO-ANT','Antioquia',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (91,'CO-ARA','Arauca',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (92,'CO-ATL','Atlántico',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (93,'CO-DC','Bogotá D.C.',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (94,'CO-BOL','Bolívar',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (95,'CO-BOY','Boyacá',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (96,'CO-CAL','Caldas',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (97,'CO-CAQ','Caquetá',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (98,'CO-CAS','Casanare',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (99,'CO-CAU','Cauca',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (100,'CO-CES','Cesar',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (101,'CO-CHO','Chocó',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (102,'CO-COR','Córdoba',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (103,'CO-CUN','Cundinamarca',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (104,'CO-GUA','Guainía',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (105,'CO-GUV','Guaviare',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (106,'CO-HUI','Huila',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (107,'CO-LAG','La Guajira',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (108,'CO-MAG','Magdalena',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (109,'CO-MET','Meta',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (110,'CO-NAR','Nariño',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (111,'CO-NSA','Norte de Santander',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (112,'CO-SAP','Providencia y Santa Catalina, Archipiélago de San Andrés',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (113,'CO-PUT','Putumayo',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (114,'CO-QUI','Quindío',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (115,'CO-RIS','Risaralda',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (116,'CO-SAN','Santander',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (117,'CO-SUC','Sucre',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (118,'CO-TOL','Tolima',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (119,'CO-VAC','Valle del Cauca',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (120,'CO-VAU','Vaupés',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (121,'CO-VID','Vichada',42,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (122,'CR','Alajuela',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (123,'CR','Cartago',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (124,'CR','Guanacaste',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (125,'CR','Heredia',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (126,'CR','Limon',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (127,'CR','Puntarenas',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (128,'CR','San Jose',47,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (129,'EC','Azuay',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (130,'EC','Bolivar',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (131,'EC','Canar',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (132,'EC','Carchi',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (133,'EC','Chimborazo',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (134,'EC','Cotopaxi',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (135,'EC','El Oro',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (136,'EC','Esmeraldas',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (137,'EC','Francisco de Orellana',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (138,'EC','Galápagos',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (139,'EC','Guayas',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (140,'EC','Imbabura',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (141,'EC','Loja',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (142,'EC','Los Rios',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (143,'EC','Manabí',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (144,'EC','Morona Santiago',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (145,'EC','Napo',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (146,'EC','Pastaza',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (147,'EC','Pichincha',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (148,'EC','Santa Elena',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (149,'EC','Santo Domingo de los Tsachilas',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (150,'EC','Sucumbios',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (151,'EC','Tungurahua',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (152,'EC','Zamora Chinchipe',53,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (153,'SV','Ahuachapan',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (154,'SV','Cabanas',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (155,'SV','Chalatenango',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (156,'SV','Cuscatlan',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (157,'SV','La Libertad',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (158,'SV','La Paz',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (159,'SV','La Union',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (160,'SV','Morazan',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (161,'SV','San Miguel',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (162,'SV','San Salvador',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (163,'SV','San Vicente',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (164,'SV','Santa Ana',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (165,'SV','Sonsonate',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (166,'SV','Usulutan',55,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (167,'ES','Galicia',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (168,'ES','Andalucía',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (169,'ES','Aragón',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (170,'ES','Canarias',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (171,'ES','Cantabria',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (172,'ES','Castilla y León',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (173,'ES','Castilla-La Mancha',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (174,'ES','Cataluña',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (175,'ES','Ciudad de Ceuta',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (176,'ES','Comunidad de Madrid',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (177,'ES','Comunidad valenciana',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (178,'ES','País Vasco',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (179,'ES','Extremadura',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (180,'ES','Illes Balears',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (181,'ES','La Rioja',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (182,'ES','Melilla',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (183,'ES','Navarra',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (184,'ES','Asturias',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (185,'ES','Murcia',60,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (186,'US-AL','Alabama',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (187,'US-AK','Alaska',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (188,'US-AR','Arkansas',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (189,'US-AZ','Arizona',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (190,'US-CA','California',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (191,'US-NC','Carolina del Norte',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (192,'US-SC','Carolina del Sur',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (193,'US-CO','Colorado',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (194,'US-DC','Columbia',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (195,'US-CT','Connecticut',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (196,'US-ND','Dakota del Norte',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (197,'US-SD','Dakota del Sur',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (198,'US-DE','Delaware',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (199,'US-FL','Florida',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (200,'US-GA','Georgia',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (201,'US-HI','Hawaii',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (202,'US-ID','Idaho',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (203,'US-RI','Rhode Island',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (204,'US-IL','Illinois',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (205,'US-IN','Indiana',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (206,'US-IA','Iowa',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (207,'US-KS','Kansas',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (208,'US-KY','Kentucky',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (209,'US-LA','Louisiana',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (210,'US-ME','Maine',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (211,'US-MD','Maryland',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (212,'US-MA','Massachusetts',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (213,'US-MI','Michigan',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (214,'US-MN','Minnesota',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (215,'US-MS','Mississippi',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (216,'US-MO','Missouri',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (217,'US-MT','Montana',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (218,'US-NE','Nebraska',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (219,'US-NV','Nevada',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (220,'US-NH','Nueva Hampshire',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (221,'US-NY','Nueva York',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (222,'US-NJ','Nueva Jersey',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (223,'US-NM','Nuevo México',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (224,'US-OK','Oklahoma',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (225,'US-OH','Ohio',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (226,'US-OR','Oregón',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (227,'US-PA','Pensilvania',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (228,'US-TN','Tennessee',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (229,'US-TX','Texas',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (230,'US-UT','Utah',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (231,'US-VT','Vermont',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (232,'US-VA','Virginia',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (233,'US-WV','Virginia Occidental',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (234,'US-WA','Washington',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (235,'US-WI','Wisconsin',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (236,'US-WY','Wyoming',62,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (237,'GT','Alta Verapaz',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (238,'GT','Baja Verapaz',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (239,'GT','Chimaltenango',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (240,'GT','Chiquimula',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (241,'GT','El Progreso',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (242,'GT','Escuintla',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (243,'GT','Guatemala',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (244,'GT','Huehuetenango',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (245,'GT','Izabal',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (246,'GT','Jalapa',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (247,'GT','Jutiapa',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (248,'GT','Peten',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (249,'GT','Quetzaltenango',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (250,'GT','Quiche',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (251,'GT','Retalhuleu',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (252,'GT','Sacatepequez',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (253,'GT','San Marcos',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (254,'GT','Santa Rosa',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (255,'GT','Solola',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (256,'GT','Suchitepequez',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (257,'GT','Totonicapan',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (258,'GT','Zacapa',79,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (259,'HN','Atlantida',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (260,'HN','Choluteca',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (261,'HN','Colon',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (262,'HN','Comayagua',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (263,'HN','Copan',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (264,'HN','Cortés',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (265,'HN','El Paraiso',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (266,'HN','Francisco Morazán',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (267,'HN','Gracias a Dios',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (268,'HN','Intibuca',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (269,'HN','Islas de la Bahía',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (270,'HN','La Paz',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (271,'HN','Lempira',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (272,'HN','Ocotepeque',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (273,'HN','Olancho',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (274,'HN','Santa Barbara',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (275,'HN','Valle',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (276,'HN','Yoro',88,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (277,'MX-AGU','Aguascalientes',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (278,'MX-BCS','Baja California Sur',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (279,'MX-BCN','Baja California',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (280,'MX-CAM','Campeche',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (281,'MX-CHP','Chiapas',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (282,'MX-CHH','Chihuahua',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (283,'MX-COA','Coahuila de Zaragoza',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (284,'MX-COL','Colima',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (285,'MX-DUR','Durango',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (286,'MX-GUA','Guanajuato',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (287,'MX-GRO','Guerrero',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (288,'MX-HID','Hidalgo',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (289,'MX-JAL','Jalisco',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (290,'MX-MEX','México',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (291,'MX-DIF','México D.F.',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (292,'MX-MIC','Michoacán de Ocampo',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (293,'MX-MOR','Morelos',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (294,'MX-NAY','Nayarit',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (295,'MX-NLE','Nuevo León',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (296,'MX-OAX','Oaxaca',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (297,'MX-PUE','Puebla',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (298,'MX-QUE','Querétaro Arteaga',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (299,'MX-ROO','Quintana Roo',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (300,'MX-SLP','San Luis Potosí',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (301,'MX-SIN','Sinaloa',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (302,'MX-SON','Sonora',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (303,'MX-TAB','Tabasco',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (304,'MX-TAM','Tamaulipas',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (305,'MX-TLA','Tlaxcala',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (306,'MX-VER','Veracruz-Llave',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (307,'MX-YUC','Yucatán',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (308,'MX-ZAC','Zacatecas',160,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (309,'NI','Boaco',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (310,'NI','Carazo',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (311,'NI','Chinandega',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (312,'NI','Chontales',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (313,'NI','Esteli',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (314,'NI','Granada',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (315,'NI','Jinotega',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (316,'NI','Leon',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (317,'NI','Madriz',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (318,'NI','Managua',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (319,'NI','Masaya',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (320,'NI','Matagalpa',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (321,'NI','Nueva Segovia',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (322,'NI','Region Autonoma Atlantico Norte',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (323,'NI','Region Autonoma Atlantico Sur',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (324,'NI','Rio San Juan',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (325,'NI','Rivas',165,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (326,'PA','Bocas del Toro',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (327,'PA','Chiriqui',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (328,'PA','Cocle',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (329,'PA','Colón',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (330,'PA','Darien',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (331,'PA','Embera-Wounaan',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (332,'PA','Herrera',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (333,'PA','San Blas',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (334,'PA','Los Santos',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (335,'PA','Ngoebe-Bugle',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (336,'PA','Panamá',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (337,'PA','Veraguas',174,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (338,'PY','Alto Paraguay',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (339,'PY','Alto Parana',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (340,'PY','Amambay',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (341,'PY','Asuncion',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (342,'PY','Boqueron',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (343,'PY','Caaguazu',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (344,'PY','Caazapa',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (345,'PY','Canindeyu',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (346,'PY','Central',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (347,'PY','Concepcion',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (348,'PY','Itapua',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (349,'PY','l Guaira',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (350,'PY','la Cordillera',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (351,'PY','Misiones',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (352,'PY','Neembucu',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (353,'PY','Paraguari',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (354,'PY','Presidente Hayes',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (355,'PY','San Pedro',176,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (356,'PE-AMA','Amazonas',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (357,'PE-ANC','Ancash',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (358,'PE-APU','Apurimac',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (359,'PE-ARE','Arequipa',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (360,'PE-AYA','Ayacucho',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (361,'PE-CAJ','Cajamarca',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (362,'PE-CAL','Callao',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (363,'PE-CUS','Cusco',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (364,'PE-HUV','Huancavelica',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (365,'PE-ICA','Ica',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (366,'PE-JUN','Junin',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (367,'PE-LAL','La Libertad',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (368,'PE-LAM','Lambayeque',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (369,'PE-LIM','Lima',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (370,'PE-LMA','Lima',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (371,'PE-LOR','Loreto',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (372,'PE-MDD','Madre de Dios',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (373,'PE-MOR','Moquegua',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (374,'PE-PAS','Pasco',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (375,'PE-PIU','Piura',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (376,'PE-PUN','Puno',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (377,'PE-HUC','Region de Huanuco',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (378,'PE-SAM','San Martín',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (379,'PE-TAC','Tacna',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (380,'PE-TUM','Tumbes',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (381,'PE-UCA','Ucayali',177,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (382,'PR','Adjuntas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (383,'PR','Aguada',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (384,'PR','Aguadilla',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (385,'PR','Aguas Buenas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (386,'PR','Aibonito',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (387,'PR','Anasco',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (388,'PR','Arecibo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (389,'PR','Arroyo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (390,'PR','Barceloneta',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (391,'PR','Barranquitas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (392,'PR','Bayamon',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (393,'PR','Cabo Rojo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (394,'PR','Caguas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (395,'PR','Camuy',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (396,'PR','Canovanas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (397,'PR','Carolina',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (398,'PR','Catano',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (399,'PR','Cayey',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (400,'PR','Ceiba',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (401,'PR','Ciales',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (402,'PR','Cidra',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (403,'PR','Coamo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (404,'PR','Comerio',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (405,'PR','Corozal',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (406,'PR','Culebra',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (407,'PR','Dorado',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (408,'PR','Fajardo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (409,'PR','Florida',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (410,'PR','Guanica',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (411,'PR','Guayama',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (412,'PR','Guayanilla',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (413,'PR','Guaynabo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (414,'PR','Gurabo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (415,'PR','Hatillo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (416,'PR','Hormigueros',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (417,'PR','Humacao',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (418,'PR','Isabela',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (419,'PR','Jayuya',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (420,'PR','Juana Diaz',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (421,'PR','Juncos',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (422,'PR','Lajas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (423,'PR','Lares',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (424,'PR','Las Marias',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (425,'PR','Las Piedras',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (426,'PR','Loiza',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (427,'PR','Luquillo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (428,'PR','Manati',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (429,'PR','Maricao',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (430,'PR','Maunabo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (431,'PR','Mayagueez',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (432,'PR','Moca',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (433,'PR','Morovis',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (434,'PR','Naguabo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (435,'PR','Naranjito',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (436,'PR','Orocovis',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (437,'PR','Patillas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (438,'PR','Penuelas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (439,'PR','Ponce',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (440,'PR','Quebradillas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (441,'PR','Rincon',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (442,'PR','Rio Grande',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (443,'PR','Sabana Grande',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (444,'PR','Salinas',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (445,'PR','San German',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (446,'PR','San Juan',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (447,'PR','San Lorenzo',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (448,'PR','San Sebastian',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (449,'PR','Santa Isabel',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (450,'PR','Toa Alta',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (451,'PR','Toa Baja',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (452,'PR','Trujillo Alto',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (453,'PR','Utuado',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (454,'PR','Vega Alta',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (455,'PR','Vega Baja',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (456,'PR','Vieques',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (457,'PR','Villalba',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (458,'PR','Yabucoa',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (459,'PR','Yauco',181,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (460,'DO','Azua',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (461,'DO','Baoruco',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (462,'DO','Barahona',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (463,'DO','Dajabon',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (464,'DO','Distrito Nacional',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (465,'DO','Duarte',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (466,'DO','El Seibo',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (467,'DO','Elias Pina',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (468,'DO','Espaillat',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (469,'DO','Hato Mayor',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (470,'DO','Hermanas Mirabal',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (471,'DO','Independencia',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (472,'DO','La Altagracia',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (473,'DO','La Romana',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (474,'DO','La Vega',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (475,'DO','Maria Trinidad Sanchez',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (476,'DO','Monsenor Nouel',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (477,'DO','Monte Cristi',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (478,'DO','Monte Plata',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (479,'DO','Pedernales',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (480,'DO','Peravia',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (481,'DO','Puerto Plata',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (482,'DO','Samana',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (483,'DO','San Cristobal',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (484,'DO','San Jose de Ocoa',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (485,'DO','San Juan',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (486,'DO','San Pedro de Macoris',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (487,'DO','Sanchez Ramirez',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (488,'DO','Santiago',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (489,'DO','Santiago Rodriguez',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (490,'DO','Santo Domingo',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (491,'DO','Valverde',187,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (492,'UY','Canelones',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (493,'UY','Colonia',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (494,'UY','Artigas',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (495,'UY','Cerro Largo',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (496,'UY','Florida',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (497,'UY','Durazno',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (498,'UY','Flores',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (499,'UY','Lavalleja',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (500,'UY','Maldonado',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (501,'UY','Montevideo',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (502,'UY','Paysandu',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (503,'UY','Rio Negro',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (504,'UY','Rivera',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (505,'UY','Rocha',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (506,'UY','Salto',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (507,'UY','San Jose',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (508,'UY','Soriano',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (509,'UY','Tacuarembo',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (510,'UY','Treinta y Tres',239,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (511,'VE','Anzoátegui',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (512,'VE','Aragua',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (513,'VE','Barinas',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (514,'VE','Bolívar',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (515,'VE','Carabobo',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (516,'VE','Caracas',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (517,'VE','Delta Amacuro',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (518,'VE','Dependencias Federales',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (519,'VE','Apure',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (520,'VE','Cojedes',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (521,'VE','Coro',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (522,'VE','Guárico',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (523,'VE','Portuguesa',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (524,'VE','Cumaná',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (525,'VE','Táchira',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (526,'VE','Estado Trujillo',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (527,'VE','Estado Vargas',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (528,'VE','Yaracuy',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (529,'VE','Lara',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (530,'VE','Mérida',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (531,'VE','Miranda',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (532,'VE','Monagas',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (533,'VE','Nueva Esparta',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (534,'VE','Amazonas',242,0);
INSERT INTO `states` (`id`,`code`,`description`,`country_id`,`is_enabled`) VALUES (535,'VE','Zulia',242,0);
